# Use postgres/example user/password credentials
version: '3.9'

services:
  databaseb:
    image: postgres
    container_name: vendas-api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_REMOTE=${POSTGRES_REMOTE}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
